/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as FacebookIndexRouteImport } from './routes/facebook/index'
import { Route as FacebookPrivacyRouteImport } from './routes/facebook/privacy'
import { Route as FacebookTermsRouteImport } from './routes/facebook/terms'
import { Route as SetupChannelRouteImport } from './routes/setup/channel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookIndexRoute = FacebookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacebookRoute,
} as any)
const FacebookPrivacyRoute = FacebookPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => FacebookRoute,
} as any)
const FacebookTermsRoute = FacebookTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => FacebookRoute,
} as any)
const SetupChannelRoute = SetupChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => SetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facebook': typeof FacebookRouteWithChildren
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/facebook/privacy': typeof FacebookPrivacyRoute
  '/facebook/terms': typeof FacebookTermsRoute
  '/setup/channel': typeof SetupChannelRoute
  '/facebook/': typeof FacebookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/facebook/privacy': typeof FacebookPrivacyRoute
  '/facebook/terms': typeof FacebookTermsRoute
  '/setup/channel': typeof SetupChannelRoute
  '/facebook': typeof FacebookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facebook': typeof FacebookRouteWithChildren
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/facebook/privacy': typeof FacebookPrivacyRoute
  '/facebook/terms': typeof FacebookTermsRoute
  '/setup/channel': typeof SetupChannelRoute
  '/facebook/': typeof FacebookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facebook'
    | '/login'
    | '/rules'
    | '/settings'
    | '/setup'
    | '/facebook/privacy'
    | '/facebook/terms'
    | '/setup/channel'
    | '/facebook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rules'
    | '/settings'
    | '/setup'
    | '/facebook/privacy'
    | '/facebook/terms'
    | '/setup/channel'
    | '/facebook'
  id:
    | '__root__'
    | '/'
    | '/facebook'
    | '/login'
    | '/rules'
    | '/settings'
    | '/setup'
    | '/facebook/privacy'
    | '/facebook/terms'
    | '/setup/channel'
    | '/facebook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacebookRoute: typeof FacebookRouteWithChildren
  LoginRoute: typeof LoginRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook/': {
      id: '/facebook/'
      path: '/'
      fullPath: '/facebook/'
      preLoaderRoute: typeof FacebookIndexRouteImport
      parentRoute: typeof FacebookRoute
    }
    '/facebook/privacy': {
      id: '/facebook/privacy'
      path: '/privacy'
      fullPath: '/facebook/privacy'
      preLoaderRoute: typeof FacebookPrivacyRouteImport
      parentRoute: typeof FacebookRoute
    }
    '/facebook/terms': {
      id: '/facebook/terms'
      path: '/terms'
      fullPath: '/facebook/terms'
      preLoaderRoute: typeof FacebookTermsRouteImport
      parentRoute: typeof FacebookRoute
    }
    '/setup/channel': {
      id: '/setup/channel'
      path: '/channel'
      fullPath: '/setup/channel'
      preLoaderRoute: typeof SetupChannelRouteImport
      parentRoute: typeof SetupRoute
    }
  }
}

interface FacebookRouteChildren {
  FacebookPrivacyRoute: typeof FacebookPrivacyRoute
  FacebookTermsRoute: typeof FacebookTermsRoute
  FacebookIndexRoute: typeof FacebookIndexRoute
}

const FacebookRouteChildren: FacebookRouteChildren = {
  FacebookPrivacyRoute: FacebookPrivacyRoute,
  FacebookTermsRoute: FacebookTermsRoute,
  FacebookIndexRoute: FacebookIndexRoute,
}

const FacebookRouteWithChildren = FacebookRoute._addFileChildren(
  FacebookRouteChildren,
)

interface SetupRouteChildren {
  SetupChannelRoute: typeof SetupChannelRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupChannelRoute: SetupChannelRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacebookRoute: FacebookRouteWithChildren,
  LoginRoute: LoginRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
