import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { api, type EmailDomainSummary, type MailboxSummary } from "@/lib/api";
import { useSession } from "@/lib/auth-client";
import { emailApi, type DomainVerification, type ProvisionInput, type ProvisionPreview } from "@/lib/email-api";

const field = "rounded-md border px-3 py-1.5 text-sm";
export function EmailSettings() {
 const { data: session } = useSession();
 const workspaces = useQuery({ queryKey: ["workspaces"], queryFn: api.listWorkspaces });
 const [selected, setSelected] = useState("");
 const workspace = workspaces.data?.workspaces.find(w => w.id === selected) ?? workspaces.data?.workspaces[0];
 return <section className="border-t pt-8 space-y-4"><h2 className="text-lg font-bold">Email domains and mailboxes</h2><p className="text-sm text-muted-foreground">Pending records do not change DNS. Owners manage lifecycle; admins can inspect readiness. Neither role grants access to private messages.</p>
 <select aria-label="Email workspace" value={workspace?.id ?? ""} onChange={e => setSelected(e.target.value)} className={field}>{workspaces.data?.workspaces.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select>
 {workspaces.isError ? <p role="alert">{workspaces.error.message}</p> : null}
 {workspace && session ? <WorkspaceEmail key={workspace.id} workspaceId={workspace.id} owner={workspace.role === "owner"} operator={workspace.role === "owner" || workspace.role === "admin"} userId={session.user.id} /> : null}</section>;
}
function WorkspaceEmail({ workspaceId, owner, operator, userId }: { workspaceId: string; owner: boolean; operator: boolean; userId: string }) {
 const cache = useQueryClient();
 const domains = useQuery({ queryKey: ["email-domains", workspaceId], queryFn: () => api.listEmailDomains(workspaceId) });
 const mailboxes = useQuery({ queryKey: ["mailboxes", workspaceId], queryFn: () => api.listMailboxes(workspaceId) });
 const users = useQuery({ queryKey: ["users"], queryFn: api.listUsers });
 const inboxes = useQuery({ queryKey: ["inboxes", workspaceId], queryFn: () => api.workspaceListInboxes(workspaceId) });
 const teams = useQuery({ queryKey: ["teams", workspaceId], queryFn: () => api.listTeams(workspaceId) });
 const [domain, setDomain] = useState("");
 const [domainId, setDomainId] = useState("");
 const [ownerId, setOwnerId] = useState("");
 const [localPart, setLocalPart] = useState("support");
 const [inboxId, setInboxId] = useState("");
 const [teamId, setTeamId] = useState("");
 const refresh = async () => { await Promise.all([cache.invalidateQueries({ queryKey: ["email-domains", workspaceId] }), cache.invalidateQueries({ queryKey: ["mailboxes", workspaceId] }), cache.invalidateQueries({ queryKey: ["assigned-mailboxes", workspaceId] })]); };
 const mutation = useMutation({ mutationFn: (action: () => Promise<unknown>) => action(), onSuccess: refresh });
 return <div className="space-y-5">
 {domains.isError || mailboxes.isError ? <p role="alert" className="text-red-600">{domains.error?.message ?? mailboxes.error?.message}</p> : null}
 {mutation.isError ? <p role="alert" className="text-red-600">{mutation.error.message}</p> : null}
 {owner ? <form className="flex gap-2" onSubmit={e => { e.preventDefault(); mutation.mutate(() => api.createEmailDomain(workspaceId, domain.trim())); }}><input aria-label="Pilot subdomain" placeholder="pilot.example.com" value={domain} onChange={e => setDomain(e.target.value)} className={field} required /><Button size="sm" disabled={mutation.isPending || !domain.trim()}>Add pending domain</Button></form> : null}
 {domains.isPending ? <p>Loading domains…</p> : domains.data?.emailDomains.length === 0 ? <p className="text-sm text-muted-foreground">No domains configured.</p> : null}
 {domains.data?.emailDomains.map(d => <DomainControls key={d.id} domain={d} owner={owner} workspaceId={workspaceId} refresh={refresh} />)}
 {owner ? <div className="rounded-lg border p-4 space-y-3"><h3 className="font-semibold">Explicit mailbox assignment</h3><p className="text-xs text-muted-foreground">Creating an address leaves receiving and sending disabled. A private address uses the selected member’s immutable username.</p>
 <select aria-label="Assignment domain" className={field} value={domainId} onChange={e => setDomainId(e.target.value)}><option value="">Choose domain…</option>{domains.data?.emailDomains.map(d => <option key={d.id} value={d.id}>{d.canonicalDomain}</option>)}</select>
 <div className="flex flex-wrap gap-2"><select aria-label="Private mailbox owner" className={field} value={ownerId} onChange={e => setOwnerId(e.target.value)}><option value="">Choose private owner…</option>{users.data?.users.map(u => <option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select><Button size="sm" disabled={mutation.isPending || !domainId || !ownerId} onClick={() => mutation.mutate(() => api.createPrivateMailbox(workspaceId, domainId, ownerId))}>Assign private mailbox</Button></div>
 <div className="flex flex-wrap gap-2"><input aria-label="Shared local part" className={field} value={localPart} onChange={e => setLocalPart(e.target.value)} /><select aria-label="Shared inbox" className={field} value={inboxId} onChange={e => setInboxId(e.target.value)}><option value="">Shared inbox…</option>{inboxes.data?.inboxes.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select><select aria-label="Shared team" className={field} value={teamId} onChange={e => setTeamId(e.target.value)}><option value="">Inbox membership only</option>{teams.data?.teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select><Button size="sm" disabled={mutation.isPending || !domainId || !inboxId || !localPart.trim()} onClick={() => mutation.mutate(() => api.createSharedMailbox(workspaceId, { emailDomainId: domainId, localPart: localPart.trim(), inboxId, teamId: teamId || null }))}>Create shared mailbox</Button></div>
 </div> : null}
 {mailboxes.data?.mailboxes.map(m => <MailboxControls key={m.id} mailbox={m} owner={owner} currentUserId={userId} users={users.data?.users ?? []} workspaceId={workspaceId} refresh={refresh} />)}
 {owner ? <BulkProvision workspaceId={workspaceId} domains={domains.data?.emailDomains ?? []} users={users.data?.users ?? []} refresh={refresh} /> : null}
 {operator ? <Operations workspaceId={workspaceId} owner={owner} /> : null}
 </div>;
}
function DomainControls({ domain, owner, workspaceId, refresh }: { domain: EmailDomainSummary; owner: boolean; workspaceId: string; refresh: () => Promise<void> }) {
 const [routing, setRouting] = useState(false); const [sending, setSending] = useState(false); const [selector, setSelector] = useState(""); const [verification, setVerification] = useState<DomainVerification | null>(null);
 const mutation = useMutation({ mutationFn: (action: () => Promise<unknown>) => action(), onSuccess: refresh });
 return <article className="rounded-lg border p-4 space-y-3"><h3 className="font-semibold">{domain.canonicalDomain}</h3><p className="text-sm">Inbound: {domain.inboundState} · Outbound: {domain.outboundState} · {domain.operatorConfirmedAt ? `Operator confirmed ${domain.operatorConfirmedAt}` : "Not confirmed"}</p>
 <details className="text-sm"><summary>Target-specific operator checklist (no automatic DNS writes)</summary><ol className="list-decimal pl-5 mt-2 space-y-1"><li>In the intended Cloudflare account, inspect the parent zone and select only {domain.canonicalDomain} under Email Routing.</li><li>Capture the dashboard MX/TXT preview. Approve only names at/below {domain.canonicalDomain}; never replace apex Workspace MX, SPF, DKIM or DMARC.</li><li>Use explicit recipient routes to this Worker. The zone-level catch-all API does not guarantee subdomain isolation; do not enable a catch-all without independently proving scope.</li><li>Onboard {domain.canonicalDomain} separately in Email Sending; copy its actual SPF/DKIM records and selector. Workers Paid and Email Service Beta access are required.</li><li>Confirm routing and sending in the provider dashboard; public DNS alone cannot prove either. Configure lifecycle subscriptions separately where available.</li></ol></details>
 {owner ? <><label className="flex gap-2 text-sm"><input type="checkbox" checked={routing} onChange={e => { setRouting(e.target.checked); setVerification(null); }} />Routing dashboard reviewed for this exact subdomain</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={sending} onChange={e => { setSending(e.target.checked); setVerification(null); }} />Sending dashboard reviewed for this exact subdomain</label><input aria-label={`DKIM selector for ${domain.canonicalDomain}`} placeholder="Provider DKIM selector (optional)" className={field} value={selector} onChange={e => { setSelector(e.target.value); setVerification(null); }} />
 <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate(async () => { setVerification(await emailApi.verify(workspaceId, domain.id, { routingConfirmed: routing, sendingConfirmed: sending, dkimSelector: selector || undefined })); })}>Check DNS / record confirmations</Button><Button size="sm" disabled={mutation.isPending || !verification?.ready || !routing || !sending} onClick={() => { if (confirm(`Activate ${domain.canonicalDomain} in MsgFlow only? Confirm approved DNS preview and provider configuration first. Mailboxes remain separately controlled.`)) mutation.mutate(() => emailApi.domainState(workspaceId, domain.id, { inboundState: "ready", outboundState: "ready", operatorConfirmed: true })); }}>Activate domain</Button><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => { if (confirm(`Suspend inbound and outbound for ${domain.canonicalDomain}? Its mailbox capabilities will be disabled.`)) mutation.mutate(() => emailApi.domainState(workspaceId, domain.id, { inboundState: "suspended", outboundState: "suspended" })); }}>Suspend</Button></div></> : <p className="text-xs text-muted-foreground">Read-only readiness. Ask a Workspace Owner to verify or change lifecycle.</p>}
 {verification ? <div className="text-xs space-y-1"><p>DNS observed {verification.checkedAt} · {verification.ready ? "Readiness checks passed" : "Not ready"}</p>{verification.observations.map(o => <p key={`${o.name}:${o.type}`}>{o.type} {o.name}: {o.values.join("; ") || "No records observed"} · {o.status}{o.expected ? ` · Expected: ${o.expected}` : ""}</p>)}</div> : null}
 {mutation.isError ? <p role="alert" className="text-sm text-red-600">{mutation.error.message}</p> : null}</article>;
}
function MailboxControls({ mailbox: m, owner, currentUserId, users, workspaceId, refresh }: { mailbox: MailboxSummary; owner: boolean; currentUserId: string; users: { id: string; name: string }[]; workspaceId: string; refresh: () => Promise<void> }) {
 const [delegate, setDelegate] = useState(""); const canDelegate = m.type === "private" && m.ownerUserId === currentUserId;
 const delegates = useQuery({ queryKey: ["mailbox-delegates", workspaceId, m.id], queryFn: () => emailApi.delegates(workspaceId, m.id), enabled: canDelegate });
 const mutation = useMutation({ mutationFn: (fn: () => Promise<unknown>) => fn(), onSuccess: async () => { await refresh(); if (canDelegate) await delegates.refetch(); } });
 return <article className="rounded-lg border p-3 space-y-2 text-sm"><h4 className="font-semibold">{m.canonicalAddress} <span className="font-normal text-muted-foreground">· {m.type}</span></h4><p>Receiving {m.isEnabled ? "enabled" : "disabled"} · Sending {m.isSendEnabled ? "enabled" : "disabled"}</p><p className="text-xs text-muted-foreground">{m.type === "private" ? `Owner: ${users.find(u => u.id === m.ownerUserId)?.name ?? m.ownerUserId}` : `Inbox: ${m.inboxId} · Team: ${m.teamId ?? "inbox membership"}`}</p>
 {owner ? <div className="flex gap-2"><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate(() => emailApi.mailboxState(workspaceId, m.id, { isEnabled: !m.isEnabled }))}>{m.isEnabled ? "Disable receiving" : "Enable receiving"}</Button><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate(() => emailApi.mailboxState(workspaceId, m.id, { isSendEnabled: !m.isSendEnabled }))}>{m.isSendEnabled ? "Disable sending" : "Enable sending"}</Button></div> : null}
 {canDelegate ? <div className="space-y-2"><p className="text-xs">Delegation grants read and send-as. Only the private mailbox owner can grant or revoke.</p><select aria-label={`Delegate for ${m.canonicalAddress}`} value={delegate} onChange={e => setDelegate(e.target.value)} className={field}><option value="">Choose member…</option>{users.filter(u => u.id !== currentUserId).map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><Button size="sm" variant="outline" disabled={!delegate || mutation.isPending} onClick={() => { if (confirm(`Grant this member read and send-as for ${m.canonicalAddress}?`)) mutation.mutate(() => emailApi.grant(workspaceId, m.id, delegate)); }}>Grant access</Button>{delegates.data?.delegates.map(d => <div key={d.userId}>{users.find(u => u.id === d.userId)?.name ?? d.userId} <Button size="sm" variant="ghost" disabled={mutation.isPending} onClick={() => mutation.mutate(() => emailApi.revoke(workspaceId, m.id, d.userId))}>Revoke</Button></div>)}{delegates.isError ? <p role="alert">Unable to read grants: {delegates.error.message}</p> : null}</div> : null}
 {mutation.isError ? <p role="alert" className="text-red-600">{mutation.error.message}</p> : null}</article>;
}
function BulkProvision({ workspaceId, domains, users, refresh }: { workspaceId: string; domains: EmailDomainSummary[]; users: { id: string; name: string }[]; refresh: () => Promise<void> }) {
 const [domain, setDomain] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [excluded, setExcluded] = useState<string[]>([]); const [preview, setPreview] = useState<ProvisionPreview | null>(null); const [reviewed, setReviewed] = useState(false);
 const body: ProvisionInput = { emailDomainId: domain, userIds: selected, excludeUserIds: excluded };
 const reset = () => { setPreview(null); setReviewed(false); };
 const mutation = useMutation({ mutationFn: async (commit: boolean) => { const result = commit ? await emailApi.provision(workspaceId, body) : await emailApi.preview(workspaceId, body); setPreview(result); setReviewed(false); if (commit) await refresh(); } });
 return <details className="rounded-lg border p-4"><summary className="font-semibold">Bulk private assignment · explicit preview required</summary><div className="mt-3 space-y-3"><p className="text-sm text-amber-800">This reserves addresses for selected users, not every current or future user. No mailboxes are automatically enabled. Record the approved preview before commit.</p><select aria-label="Bulk domain" className={field} value={domain} onChange={e => { setDomain(e.target.value); reset(); }}><option value="">Choose domain…</option>{domains.map(d => <option key={d.id} value={d.id}>{d.canonicalDomain}</option>)}</select>
 {users.map(u => <div key={u.id} className="flex gap-4 text-sm"><label><input type="checkbox" checked={selected.includes(u.id)} onChange={e => { setSelected(e.target.checked ? [...selected, u.id] : selected.filter(id => id !== u.id)); reset(); }} /> {u.name}</label><label><input type="checkbox" checked={excluded.includes(u.id)} onChange={e => { setExcluded(e.target.checked ? [...excluded, u.id] : excluded.filter(id => id !== u.id)); reset(); }} /> Explicitly exclude</label></div>)}
 <Button size="sm" variant="outline" disabled={!domain || !selected.length || mutation.isPending} onClick={() => mutation.mutate(false)}>Preview exact assignments</Button>
 {preview ? <><ul className="space-y-1 text-sm">{preview.entries.map(e => <li key={e.userId}>{users.find(u => u.id === e.userId)?.name ?? e.userId} → {e.address ?? "No address"} · {e.action}{e.reason ? ` · ${e.reason}` : ""}</li>)}</ul><label className="flex gap-2 text-sm"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I have reviewed and recorded this exact preview and its exclusions.</label><Button size="sm" disabled={!reviewed || mutation.isPending || !preview.entries.some(e => e.action === "create") || preview.entries.some(e => e.action === "error")} onClick={() => { if (confirm("Commit these private address reservations? Eligibility is rechecked by the server; review the returned result for skips or conflicts.")) mutation.mutate(true); }}>Commit reviewed assignments</Button></> : null}
 {mutation.isError ? <p role="alert" className="text-sm text-red-600">{mutation.error.message}</p> : null}</div></details>;
}
function Operations({ workspaceId, owner }: { workspaceId: string; owner: boolean }) {
 const operations = useQuery({ queryKey: ["email-operations", workspaceId], queryFn: () => emailApi.operations(workspaceId), refetchInterval: 15000 });
 const replay = useMutation({ mutationFn: (id: string) => emailApi.replay(workspaceId, id), onSuccess: () => { void operations.refetch(); } });
 return <details className="rounded-lg border p-4"><summary className="font-semibold">Email operations · quarantine, replay and audit</summary><div className="mt-3 space-y-3 text-sm"><p>Metadata only. Replay resumes an eligible durable inbound record; it is not an outbound resend. Uncertain sends require provider reconciliation, never a new request ID.</p><Button size="sm" variant="outline" onClick={() => void operations.refetch()}>Refresh operations</Button>
 {operations.isPending ? <p>Loading operational state…</p> : null}{operations.isError ? <p role="alert" className="text-red-600">Operations unavailable: {operations.error.message}</p> : null}
 <h4 className="font-semibold">Inbound / quarantine</h4>{operations.data?.ingress.map(i => <div key={i.id} className="rounded border p-2">{i.id} · {i.state} · {i.receivedAt}{i.reason ? ` · ${i.reason}` : ""}{owner && i.replayable ? <Button size="sm" variant="outline" disabled={replay.isPending} onClick={() => { if (confirm(`Replay eligible inbound record ${i.id} after correcting the cause? Check the result and timeline for duplicates.`)) replay.mutate(i.id); }}>Replay ingress</Button> : null}</div>)}
 <h4 className="font-semibold">Outbound attempts</h4>{operations.data?.outbound.map(o => <p key={o.clientMessageId}>{o.clientMessageId} · {o.state === "accepted" ? "provider accepted (not delivered)" : o.state} · {o.updatedAt}{o.error ? ` · ${o.error}` : ""}</p>)}
 <h4 className="font-semibold">Audit</h4>{operations.data?.audit.map(a => <p key={a.id}>{a.createdAt} · {a.action} · actor {a.actorId ?? "system"} · {a.targetId}</p>)}
 {replay.isError ? <p role="alert" className="text-red-600">{replay.error.message}</p> : null}</div></details>;
}
